# Devices config
device:
  pi_3:
    ip: "192.168.178.25"
    sensors:
      - joystick
      - accelerometer
      - humidity_temp_pressure
  pi_4:
    ip: "192.168.178.29"
    sensors:
      - sound


post_url: http://fastapi-siddhi:8000

# Event config
event:
  joystick:
    data_generation_interval: 0.1

  accelerometer:
    data_generation_interval: 0.4

  humidity_temp_pressure:
    data_generation_interval: 0.5
  
  sound:
    data_generation_interval: 0.0
  