# Devices config
device:
  pi_1:
    ip: xxxx
    sensors:
      - sound
  pi_3:
    ip: xxxx
    sensors:
      - joystick
      - accelerometer
      - humidity_temp_pressure


post_url: http://fastapi-siddhi:8000

# Event config
event:
  joystick:
    data_generation_interval: 0.1

  accelerometer:
    data_generation_interval: 0.4

  humidity_temp_pressure:
    data_generation_interval: 0.5
  
  sound:
    data_generation_interval: 0.0
  