# Devices config
device:
  pi_3:
    ip: "192.168.178.25" # home
    # ip: "192.168.1.143" # uni
    # ip: "192.168.1.143" # iphone Kris
    sensors:
      - joystick
      - accelerometer
      - humidity_temp_pressure
  pi_4:
    ip: "192.168.178.29" # home
    # ip: "192.168.1.144" # uni
    # ip: "192.168.1.144" # iphone Kris
    sensors:
      - sound


post_url: http://fastapi-siddhi:8000

# Event config
event:
  joystick:
    data_generation_interval: 0.1

  accelerometer:
    data_generation_interval: 0.4

  humidity_temp_pressure:
    data_generation_interval: 0.5
  
  sound:
    data_generation_interval: 0.0
  

  # timestamp in seconds: only hour, minutes, seconds

  # connect to the pis from the laptop in the lab network:
   # pi3: sshpass -p 45687231 ssh -o StrictHostKeyChecking=no pi@192.168.1.143
   # pi4: sshpass -p 35468432 ssh -o StrictHostKeyChecking=no pi@192.168.1.144
