version: '3.8'
services:
  sensor-reader:
    privileged: true
    build:
      context: .
      dockerfile: ./sensors/Dockerfile
    platform: linux/arm/v7
    # image: piankris/sensor-reader:armv7
    depends_on:
      - fastapi-siddhi
    environment:
      - DEVICE_ID=${DEVICE_ID}
    # volumes:
    #   - ./sensor-reader:/app
    # Add any additional configuration for the sensor-reader service
  
  fastapi-siddhi:
    # image: piankris/fastapi-siddhi:armv7
    privileged: true
    build:
      context: .
      dockerfile: ./server/Dockerfile
    platform: linux/arm/v7
    ports:
      - 8000:8000
    # Add any additional configuration for the fastapi-siddhi service
