device_id:
  pi_3: 
  - joystick
  - accelerometer
  - humidity_temp_pressure
  pi_1:
    - sound

post_url: http://fastapi-siddhi:8000

event:
  joystick:
    data_generation_interval: 0.1

  accelerometer:
    data_generation_interval: 0.4

  humidity_temp_pressure:
    data_generation_interval: 0.5
  
  sound:
    data_generation_interval: 0.0
  